### ISSUE TITLE
Issue with running orclbm_main

### ISSUE THREAD

**Issue by swapnilKeshettivar** [CRFlibrary/CRF_BQCloud#2]
**python orclbm_main.py --bqpid setupcrf --bqtbl GL_BALANCES**  syntax gives an error in the code 

**File "/home/swapnil_keshetty/CRF_BQCloud/orclbm/orclbm/orclbm.py", line 119, in read
    cur.execute('select '+ self._fields +' from '+ self._table + self._query)
TypeError: cannot concatenate 'str' and 'dict' objects**

**Comment by finarb** [comment]
what was the call? i.e. the full command

**Comment by finarb** [comment]
resolved for now
